/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#4ae176",
        "on-secondary-fixed-variant": "#5c3187",
        "on-surface-variant": "#444653",
        "on-tertiary-fixed": "#002109",
        "primary-container": "#546cd7",
        "on-primary-fixed": "#001356",
        "on-primary-fixed-variant": "#1f3ba6",
        "surface-container": "#eceef3",
        "on-primary-container": "#fffbff",
        "surface-container-high": "#e7e8ee",
        "tertiary-container": "#00873b",
        "background": "#f8f9ff",
        "inverse-surface": "#2e3135",
        "primary": "#3953bd",
        "surface-variant": "#e1e2e8",
        "tertiary": "#006b2d",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-container": "#5a3086",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#005321",
        "secondary-fixed-dim": "#dcb8ff",
        "primary-fixed-dim": "#b9c3ff",
        "surface-tint": "#3c55bf",
        "error-container": "#ffdad6",
        "secondary-fixed": "#f0dbff",
        "secondary": "#754aa1",
        "surface": "#f8f9ff",
        "on-surface": "#191c20",
        "on-primary": "#ffffff",
        "outline-variant": "#c5c5d5",
        "surface-container-low": "#f2f3f9",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff0f6",
        "inverse-primary": "#b9c3ff",
        "surface-dim": "#d8dae0",
        "surface-bright": "#f8f9ff",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "tertiary-fixed": "#6bff8f",
        "secondary-container": "#ce9ffd",
        "on-background": "#191c20",
        "on-tertiary-container": "#f7fff3",
        "surface-container-highest": "#e1e2e8",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dde1ff",
        "outline": "#757684"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}